---
resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource


resources:
- name: source-repo
  type: git
  source:
    uri: https://github.com/patrick-huber-pivotal/cf-policy-pipeline
    username: ((git_username))
    password: ((git_password))

- name: azure-bucket
  type: azure-blobstore
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: ((container))
    versioned_file: database.db

jobs:
- name: create-database
  plan:
  - get: source-repo
  - task: export-cf-data
    file: source-repo/tasks/export-cf-data/task.yml
    params:
      CF_USERNAME: ((cf_username))
      CF_TARGET: ((cf_target))
      CF_PASSWORD: ((cf_password))
  - task: populate-database
    file: source-repo/tasks/populate-database/task.yml  
  - put: azure-bucket
    file: database/*.db