---
resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource


resources:
- name: source-repo
  type: git
  source:
    uri: https://github.com/patrick-huber-pivotal/cf-policy-pipeline
    username: ((git_username))
    password: ((git_password))

- name: bucket
  type: azure-blobstore
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: ((container))
    versioned_file: database.db

jobs:
- name: create-database
  plan:
  - get: source-repo
  - task: export-data
    file: source-repo/tasks/export-data/task.yml
    params:
      CF_USERNAME: ((cf_username))
      CF_TARGET: ((cf_target))
      CF_PASSWORD: ((cf_password))
      OM_USERNAME: ((om_username))
      OM_PASSWORD: ((om_password))
      OM_TARGET: ((om_target))
      OM_SKIP_SSL_VALIDATION: ((om_skip_ssl_validation))
  - task: populate-database
    file: source-repo/tasks/populate-database/task.yml  
  - put: bucket
    params:
      file: database/database.db

- name: apps-without-autoscaler-query
  plan:
  - get: source-repo
  - get: bucket
  - task: query
    file: source-repo/tasks/query/task.yml
    input_mapping:
      database: bucket
    params:
      QUERY: |
         SELECT a.Name as APP, 
                sp.Name as SPACE, 
                o.Name as ORG
         FROM APPS a
         LEFT JOIN SERVICE_BINDINGS sb
           on sb.APP_ID = a.ID
         LEFT JOIN SERVICE_INSTANCES si
           on si.ID = sb.SERVICE_INSTANCE_ID
         LEFT JOIN SERVICES s
           on  s.ID = si.SERVICE_ID
           and s.NAME = 'app-autoscaler'
         LEFT JOIN SPACES sp
           on a.SPACE_ID = sp.ID
         LEFT JOIN ORGANIZATIONS o
           on o.ID = sp.ORGANIZATION_ID
         WHERE sb.ID is null
           and o.Name not in ("system");

- name: certificates-query
  plan:
  - get: source-repo
  - get: bucket
  - task: query
    file: source-repo/tasks/query/task.yml
    input_mapping:
      database: bucket
    params:
      QUERY: |
        SELECT * 
        FROM CERTIFICATES
        ORDER BY datetime(VALID_UNTIL) ASC;

- name: certificate-authorities-query
  plan:
  - get: source-repo
  - get: bucket
  - task: query
    file: source-repo/tasks/query/task.yml
    input_mapping:
      database: bucket
    params:
      QUERY: |
        SELECT * 
        FROM CERTIFICATE_AUTHORITIES
        ORDER BY datetime(EXPIRES_ON) ASC;

- name: certificates-expiring-in-3-months
  plan: 
  - get: source-repo
  - get: bucket
  - task: query
    file: source-repo/tasks/query/task.yml
    input_mapping:
      database: bucket
    output_mapping:
      results: results
    params:
      QUERY: |
        SELECT * 
        FROM CERTIFICATE_AUTHORITIES
        ORDER BY datetime(EXPIRES_ON) ASC;
  - in_parallel:
    - task: alert
      file: source-repo/tasks/alert-rows-exist/task.yml
      input_mapping:
        results: results
      params:
        SKIP_HEADER: true
        FILE: report.csv