---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickhuber/policy-base
    tag: "1.1"

inputs:
- name: source-repo

outputs:
- name: cf-data

run:
  path: source-repo/tasks/export-data/task.sh

params:
    # The cloud foundry username to login and query the system (cf cli username)
    CF_USERNAME:
    # The api target for cloud foundry (cf cli target)
    CF_TARGET:
    # The cloud foundry password to login and query the system (cf cli password)
    CF_PASSWORD:
    # The cloud foundry system domain
    CF_SYS_DOMAIN:
    # The ops manager url
    OM_TARGET:
    # The ops manager username
    OM_USERNAME:
    # The ops manager password
    OM_PASSWORD:
    # Skip ssl validation for the ops manager api
    OM_SKIP_SSL_VALIDATION:
