---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: source-repo
- name: cf-data

outputs:
- name: database

run:
  path: source-repo/tasks/populate-database/task.sh