---
platform: linux
    
image_resource:
  type: docker-image
  source:
    repository: patrickhuber/sqlite
    tag: "3.31.0"
    
inputs:
- name: database
- name: source-repo
    
run:
  path: source-repo/tasks/query/task.sh