---
platform: linux
    
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest
    
inputs:
- name: database
- name: source-repo
    
run:
  path: source-repo/tasks/query/task.sh