---
platform: linux
    
image_resource:
  type: docker-image
  source:
    repository: patrickhuber/policy-base
    tag: "1.3"
    
inputs:
- name: database
- name: source-repo
    
outputs:
- name: results

run:
  path: source-repo/tasks/query/task.sh
