---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: source-repo
- name: database

run:
  path: source-repo/tasks/applications-without-autoscaler/task.sh